### ISSUE TITLE
TLS verification problem

### ISSUE THREAD

**Issue by Hasimir** [Selfnet/hkp4py#8]
There's a problem if the keyserver is set to use one of the pool hostnames.  When the request is made to whichever keyserver is selected, the result is that the SSL check fails since it won't match the hostname check in requests.

There are two main approaches to addressing this type of problem.

 1. Use a try/except statement which runs it with `verify=False` when an exception is raised.
 2. Use a try/except statement which runs it with the `url` set to a specific host in the pool.  This will probably require nested try/except statements in case there are host specific SSL or connection issues.

**Comment by Cellebyte** [comment]
So it is not an real issue. We can add the CA to the `hkp4py` package or download it on the fly from the following location [CA.pem](https://sks-keyservers.net/sks-keyservers.netCA.pem). Other pools will not be supported. But this is not an issue. So adding this functionality should not be that hard.



# hkps.pool.sks-keyservers.net

This is a pool containing only servers available using hkps. Regular A and AAAA and SRV records are included for port 443 servers, and a lookup is performed for _pgpkey-https._tcp on the individual servers to determine if a hkps enabled service is listening on another port. At this point, however, servers not running on port 443 are not included.

This pool only include servers that have been certified by the sks-keyservers.net CA, of which the certificate can be found at [CA.pem](https://sks-keyservers.net/sks-keyservers.netCA.pem).

For GnuPG 1.4 and 2.0 installations this can be used by using the following parameters in gpg.conf:

## ~/.gnupg/gpg.conf:
```ini
  keyserver hkps://hkps.pool.sks-keyservers.net
  keyserver-options ca-cert-file=/path/to/CA/sks-keyservers.netCA.pem
```

GnuPG 2.1 users prior to version 2.1.11 (starting with this version the certificate is enabled by default for this pool) want to add the following in dirmngr.conf:

## ~/.gnupg/dirmngr.conf:
```ini
   hkp-cacert /path/to/CA/sks-keyservers.netCA.pem
```

**Comment by Hasimir** [comment]
This is all accurate, but we shouldn't bank on everyone having the right config in place already; that would be foolish.

The copy of the `sks-keyservers.netCA.pem` file will be located in the directory returned by `gpgconf --list-dirs datadir`.  So something like this ought to do the trick:

``` python
import os.path
import requests
import subprocess
import sys

keyserver = "hkps://pool.sks-keyservers.net"

if sys.platform == "win32":
    gpgconfcmd = "gpgconf.exe --list-dirs datadir"
else:
    gpgconfcmd = "gpgconf --list-dirs datadir"

process = subprocess.Popen(gpgconfcmd.split(),
                           stdout=subprocess.PIPE)
procom = process.communicate()
if sys.version_info[0] == 2:
    datadir = procom[0].strip()
else:
    datadir = procom[0].decode().strip()

pempath = "{0}/sks-keyservers.netCA.pem".format()

if os.path.exists(pempath) is True:
    pemfile = pempath
else:
	pemfile = "https://sks-keyservers.net/sks-keyservers.netCA.pem"

try:
    response = requests.get(keyserver)
except:
    response = requests.get(keyserver, verify=pemfile)
```

**Comment by Cellebyte** [comment]
Need to investigate.
